# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudShopping' do
pod 'Masonry'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'YYModel'
pod 'SDCycleScrollView'
end
